import * as THREE from 'three';
import * as C from './core';
import * as A from './aux';
import * as SP from './smallParts';
import * as V from './valvetrain';

/** Raw part builders (no fastener hardware); see assets.ts for the exported set. */
export const RAW_BUILDERS: Record<string, () => THREE.Object3D> = {
  'crankcase-right': () => C.crankcaseHalf(1),
  'crankcase-left': () => C.crankcaseHalf(-1),
  'main-bearings': C.mainBearings,
  crankshaft: C.crankshaft,
  'crank-gears': C.crankGears,
  conrod: C.conrod,
  piston: C.piston,
  cylinder: C.cylinder,
  'cylinder-head': C.cylinderHead,
  'valve-set-1': () => V.valveSet(1),
  'valve-set-2': () => V.valveSet(2),
  'valve-set-3': () => V.valveSet(3),
  'valve-set-4': () => V.valveSet(4),
  'valve-set-5': () => V.valveSet(5),
  'valve-set-6': () => V.valveSet(6),
  'cam-housing-right': () => V.camHousing(1),
  'cam-housing-left': () => V.camHousing(-1),
  'valve-cover-upper-right': () => V.pocketValveCover(C.valveCover(1, true), 1, true),
  'valve-cover-lower-right': () => V.relieveCoverLead(V.pocketValveCover(C.valveCover(1, false), 1, false), 1, false, A.ignitionLeads()),
  'valve-cover-upper-left': () => V.pocketValveCover(C.valveCover(-1, true), -1, true),
  'valve-cover-lower-left': () => V.relieveCoverLead(V.pocketValveCover(C.valveCover(-1, false), -1, false), -1, false, A.ignitionLeads()),
  'camshaft-right': () => V.camshaft(1),
  'camshaft-left': () => V.camshaft(-1),
  'rockers-right': () => V.rockers(1),
  'rockers-left': () => V.rockers(-1),
  'timing-chain-right': () => C.timingChain(1),
  'timing-chain-left': () => C.timingChain(-1),
  'cam-sprocket-right': () => C.camSprocket(1),
  'cam-flange-right': () => C.camFlange(1),
  'cam-flange-left': () => C.camFlange(-1),
  'distributor-clamp': () => A.distributorClamp(),
  'fan-hub': () => A.fanHub(),
  'airbox-struts': () => A.airboxStruts(),
  'warm-up-regulator': () => A.warmUpRegulator(),
  'ignition-leads': () => A.ignitionLeads(),
  'adjuster-cover-right': () => SP.adjusterCoverPart(1),
  'adjuster-cover-left': () => SP.adjusterCoverPart(-1),
  'cam-sprocket-left': () => C.camSprocket(-1),
  'chain-tensioner-right': () => C.chainTensioner(1),
  'chain-tensioner-left': () => C.chainTensioner(-1),
  'chain-housing-right': () => C.chainHousing(1),
  'chain-housing-left': () => C.chainHousing(-1),
  'chain-housing-lid-right': () => C.chainHousingLid(1),
  'chain-housing-lid-left': () => C.chainHousingLid(-1),
  'intermediate-shaft': C.intermediateShaft,
  'fan-housing': A.fanHousing,
  'fan-impeller': A.fanImpeller,
  alternator: A.alternator,
  'fan-pulley': A.fanPulley,
  'crank-pulley': A.crankPulley,
  'fan-belt': A.fanBelt,
  'upper-air-guide': A.upperAirGuide,
  'oil-cooler': A.oilCooler,
  'oil-thermostat': A.oilThermostat,
  'breather-lid': A.breatherLid,
  'sump-plate': A.sumpPlate,
  'oil-pump': A.oilPump,
  plenum: A.plenum,
  'air-filter': A.airFilter,
  'air-cleaner-lid': A.airCleanerLid,
  'intake-runner-1': () => A.intakeRunner(1),
  'intake-runner-2': () => A.intakeRunner(2),
  'intake-runner-3': () => A.intakeRunner(3),
  'intake-runner-4': () => A.intakeRunner(4),
  'intake-runner-5': () => A.intakeRunner(5),
  'intake-runner-6': () => A.intakeRunner(6),
  injector: A.injector,
  'mixture-control-unit': A.mixtureControlUnit,
  'fuel-lines': A.fuelLines,
  distributor: A.distributor,
  'spark-plug': A.sparkPlug,
  'heat-exchanger-right': () => A.heatExchanger(1),
  'heat-exchanger-left': () => A.heatExchanger(-1),
  muffler: A.muffler,
  flywheel: A.flywheel,
  'clutch-disc': A.clutchDisc,
  'pressure-plate': A.pressurePlate,
};
