/** Generates docs/parts-checklist.md from src/data/checklist.ts + docs/catalog/engine-lines.json. Run: npx tsx scripts/checklist-doc.ts */
import { writeFileSync } from 'node:fs';
import { evaluate } from './checklistEval';
import { CHECKLIST_GROUPS } from '../src/data/checklist';
import { ILLUSTRATIONS } from '../src/data/catalog';

const { rows, status, errors } = evaluate();
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }
const esc = (s: string) => s.replace(/\|/g, '\\|');
const tot = { modelled: 0, na: 0, alt: 0, auto: 0, missing: 0 } as Record<string, number>;
for (const s of status.values()) tot[s.kind]++;
const counted = tot.modelled + tot.na + tot.alt + tot.missing;
const out: string[] = [
  '# Parts checklist (1978 911 SC, US, 3.0 L, engine type 930/03-04)', '',
  '_Generated by `npx tsx scripts/checklist-doc.ts` from `src/data/checklist.ts`. `tests/checklist.test.ts` checks it against the model: every claimed quantity has to exist as geometry (parts, fastener-set instances, small-part instances or asserted per-part features), and nothing is counted twice._', '',
  'Every line from the PET catalogue illustrations in `docs/catalog/engine-lines.json` is listed below with one of these statuses:', '',
  '- **modelled**: it is in the 3D model. The source column names the part, fastener set or small-part set (`× n` = instances counted; `stud`/`washer`/`spring`/`tab` = that feature of the fastener set).',
  '- **N/A**: it is in the catalogue but deliberately not modelled. The reason is given.',
  '- **alt**: an alternative row for the same position (other part number, supersession or variant). The position itself is handled by another row.',
  '- **excluded**: a row for another model year, engine number range, model or RHD. It does not apply to this engine.',
  '- **MISSING**: still to be modelled.', '',
  'Illustration 108-00 (air injection) is outside the checklist and is not modelled.', '',
  '## Totals', '',
  '| status | lines |', '|---|---|',
  `| modelled | ${tot.modelled} |`, `| N/A (with reason) | ${tot.na} |`, `| alternative rows | ${tot.alt} |`, `| excluded (not this engine) | ${tot.auto} |`, `| **MISSING** | ${tot.missing} |`,
  `| countable lines (all but excluded) | ${counted} |`, '',
];
for (const g of CHECKLIST_GROUPS) {
  const rs = rows.filter((r) => r.ill === g);
  out.push(`## ${g}: ${ILLUSTRATIONS[g]?.title ?? ''}`, '', '| pos | part no. | description | qty | status | source / reason |', '|---|---|---|---|---|---|');
  for (const r of rs) {
    const s = status.get(r.key)!;
    const [st, src] = s.kind === 'modelled' ? ['modelled', s.claims.map((c) => `\`${c.by}\`${c.what && c.what !== 'item' ? ` ${c.what}` : ''}${c.n !== undefined ? ` × ${c.n}` : ''}${c.note ? ` (${c.note})` : ''}`).join(' + ')]
      : s.kind === 'na' ? ['N/A', s.why] : s.kind === 'alt' ? ['alt', `alternative to ${s.of}`] : s.kind === 'auto' ? ['excluded', s.why] : ['**MISSING**', s.why];
    out.push(`| ${r.pos} | ${r.pn} | ${esc(r.desc)} | ${r.qty} | ${st} | ${esc(src)} |`);
  }
  out.push('');
}
writeFileSync(new URL('../docs/parts-checklist.md', import.meta.url), out.join('\n'));
console.log(tot);
