/** Generates docs/parts-checklist.md from src/data/checklist.ts + docs/catalog/engine-lines.json. Run: npx tsx scripts/checklist-doc.ts */
import { writeFileSync } from 'node:fs';
import { evaluate } from './checklistEval';
import { CHECKLIST_GROUPS } from '../src/data/checklist';
import { ILLUSTRATIONS } from '../src/data/catalog';

const { rows, status, errors } = evaluate();
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }
const esc = (s: string) => s.replace(/\|/g, '\\|');
const tot = { modelled: 0, na: 0, alt: 0, auto: 0, missing: 0 } as Record<string, number>;
for (const s of status.values()) tot[s.kind]++;
const counted = tot.modelled + tot.na + tot.alt + tot.missing;
const out: string[] = [
  '# Parts checklist (1978 911 SC, US, 3.0 L, engine type 930/04)', '',
  '_Generated by `npx tsx scripts/checklist-doc.ts` from `src/data/checklist.ts`. `tests/checklist.test.ts` checks it against the model: every claimed quantity has to exist as geometry (parts, fastener-set instances, small-part instances or asserted per-part features), and nothing is counted twice._', '',
  'Every line from the PET catalogue illustrations in `docs/catalog/engine-lines.json` is listed below with one of these statuses:', '',
  '- **modelled**: it is in the 3D model. The source column names the part, fastener set or small-part set (`× n` = instances counted; `stud`/`washer`/`spring`/`tab` = that feature of the fastener set).',
  '- **N/A**: it is in the catalogue but deliberately not modelled. The reason is given.',
  '- **alt**: an alternative row for the same position (other part number, supersession or variant). The position itself is handled by another row.',
  '- **excluded**: a row for another model year, engine number range, model or RHD. It does not apply to this engine.',
  '- **MISSING**: still to be modelled.', '',
  'The shipped engine is the 1978 US type 930/04. Air injection (108-00), the heater blower (108-10) and EGR (202-05) are in the checklist.', '',
  '## Totals', '',
  '| status | lines |', '|---|---|',
  `| modelled | ${tot.modelled} |`, `| N/A (with reason) | ${tot.na} |`, `| alternative rows | ${tot.alt} |`, `| excluded (not this engine) | ${tot.auto} |`, `| **MISSING** | ${tot.missing} |`,
  `| countable lines (all but excluded) | ${counted} |`, '',
];
for (const g of CHECKLIST_GROUPS) {
  const rs = rows.filter((r) => r.ill === g);
  out.push(`## ${g}: ${ILLUSTRATIONS[g]?.title ?? ''}`, '', '| pos | part no. | description | qty | status | source / reason |', '|---|---|---|---|---|---|');
  for (const r of rs) {
    const s = status.get(r.key)!;
    const [st, src] = s.kind === 'modelled' ? ['modelled', s.claims.map((c) => `\`${c.by}\`${c.what && c.what !== 'item' ? ` ${c.what}` : ''}${c.n !== undefined ? ` × ${c.n}` : ''}${c.note ? ` (${c.note})` : ''}`).join(' + ')]
      : s.kind === 'na' ? ['N/A', s.why] : s.kind === 'alt' ? ['alt', `alternative to ${s.of}`] : s.kind === 'auto' ? ['excluded', s.why] : ['**MISSING**', s.why];
    out.push(`| ${r.pos} | ${r.pn} | ${esc(r.desc)} | ${r.qty} | ${st} | ${esc(src)} |`);
  }
  out.push('');
}
out.push(
  '## Top-end dimensions (batch 1)', '',
  'These are the sizes the cam housings, camshafts, rockers and valves are built to. A size marked unverified has not been checked against Wayne Dempsey, *How to Rebuild and Modify Porsche 911 Engines 1965–1989*.', '',
  '| Item | Value | Source | Dempsey |',
  '|---|---|---|---|',
  '| Lash, cold, in and ex | 0.10 mm at the adjuster ball; pad on the base circle | Wayne Dempsey, “911 Valve Adjustment” | verified |',
  '| Intake / exhaust head | Ø49 mm / Ø41.5 mm | Catalogue 930.105.409 / 930.105.419; previous model | not re-measured |',
  '| Valve angle | 25.5° in / 30.25° ex (55.75° included) | Pelican forum 851122 | unverified |',
  '| Valve length | 110.1 mm intake / 108.4 mm exhaust | Design911 and KS 3051 | unverified |',
  '| Stem | Ø9 mm, three keeper grooves | Stem size is the common 911 figure; three beads are the 901.105.417.00 photo | unverified |',
  '| Installed spring height | 34.5 mm | Bentley 911 SC spec 34.5 ± 0.3 mm (DDK quotation). Not Dempsey | unverified |',
  '| Spring diameters | outer centre Ø20.4 mm, inner Ø14.2 mm | Scaled to clear the cam-housing stud nuts. The spring photo shows a larger outer coil | unverified |',
  '| Cam journal / housing bore | Ø46.7 mm / Ø47.1 mm, four webs | Audit photos read about Ø47. Peak lobe radius 22.4 mm is under the journal so the cam slides in from the chain end | unverified |',
  '| Lobe | base radius 14.7 mm, lift 7.75 mm intake / 6.90 mm exhaust | FVD 930 105 147 17 / Cat Cams. Peaks stay under 22.85 mm | unverified |',
  '| Cam shank | Ø28 mm | About 0.6 × the journal on the FVD photo | unverified |',
  '| Cam nose | r 11 mm, Woodruff key, external M22 | Key, washer and nut still use `CAM_NOSE`. Flange OD 62 mm so the dowel holes clear the hub | key / nut unchanged |',
  '| Cam dowel | Ø6 × 14 mm, 2 mm proud of the sprocket, tail in the flange hole | 900 243 001 00, Stoddard 6 × 14. Existing `cam-pin-*`, circle radius 24 mm | parts listing |',
  '| Valve covers | both banks match the cam-housing seat | Left cover no longer overhangs the flywheel end by 30 mm. Nuts stay on the ear bosses | — |',
  '| Rocker shaft | Ø18 × 50 mm, hollow, two grooves, slotted | Photo of 901.105.342.04 | unverified |',
  '| Shaft screw / nut | M6 pan head 999.067.008.00; nut 901.105.376.02 | Kat 502 illustration 103-10 positions 45 and 47 | catalogue |',
  '| Rocker ratio | about 1.47 average; about 1.64 in / 1.58 ex at the nose | Pelican forum 1054198 is the published band (about 1.2–1.3 closed, about 1.45 at the nose). This forging is higher because the lift targets fix the average | measured |',
  '',
);
writeFileSync(new URL('../docs/parts-checklist.md', import.meta.url), out.join('\n'));
console.log(tot);
